{{- $svc := (index .Values "event-loop") | default dict }}
{{- if (get $svc "enabled" | default false) }}
{{- $context := dict "Values" $svc "Chart" (dict "Name" "event-loop") "Release" .Release }}

---
{{ include "kind-microservice-base.deployment" $context }}

---
{{ include "kind-microservice-base.service" $context }}

{{- end }}
