#!/usr/bin/env bash
# Build values-k3s-images.yaml with pinned GHCR image tags (commit SHAs).
#
# CI tags every image as ghcr.io/<org>/<package>:<github.sha>, so the SHA equals the
# commit that triggered the last successful "Build and Push Image" workflow on main.
#
# Resolution order per service:
#   1. GHCR package versions API  — needs gh auth with read:packages
#   2. Latest commit on main       — needs gh auth with repo (or public repo)
#
# Auth on the VPS (pick one):
#   gh auth login -s read:packages,repo
#   gh auth refresh -h github.com -s read:packages,repo
#   GH_TOKEN=<PAT_with_read:packages> ./scripts/fetch-image-tags.sh
#
# Usage:
#   ./scripts/fetch-image-tags.sh > /root/chatdetective/values-k3s-images.yaml
set -euo pipefail

ORG="${ORG:-ChatDetectiveORG}"

# Helm chart key -> GHCR package name (IMAGE_NAME in deploy.yml)
declare -A PACKAGES=(
  [api-gateway]=api-gateway
  [command-handler]=command-handler
  [mailing-service]=mailing-service
  [message-sender]=message-sender
  [event-loop]=event-loop
  [payment-service]=payment-service
  [chat-export-service]=chat-export-service
  [business-events-new]=business-events-new-handler
  [business-events-edited]=business-events-edited-handler
)

# Helm chart key -> GitHub source repository (for main-branch fallback)
declare -A REPOS=(
  [api-gateway]=api-gateway
  [command-handler]=command-handler
  [mailing-service]=mailing-service
  [message-sender]=messgae-sender
  [event-loop]=event-loop
  [payment-service]=payment-service
  [chat-export-service]=chat-export-service
  [business-events-new]=business-events-new-handler
  [business-events-edited]=business-events-edited-handler
)

if ! command -v gh >/dev/null; then
  echo "ERROR: gh (GitHub CLI) is required. Install: https://cli.github.com/" >&2
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "ERROR: gh is not authenticated. Run: gh auth login -s read:packages,repo" >&2
  exit 1
fi

sha_from_ghcr() {
  local pkg="$1"
  gh api "/orgs/${ORG}/packages/container/${pkg}/versions?per_page=20" \
    --jq '.[].metadata.container.tags[]' 2>/dev/null \
    | grep -E '^[0-9a-f]{40}$' \
    | head -1
}

sha_from_main() {
  local repo="$1"
  gh api "/repos/${ORG}/${repo}/commits/main" --jq '.sha' 2>/dev/null \
    | grep -E '^[0-9a-f]{40}$'
}

echo "# Generated by fetch-image-tags.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "# Each tag is a commit SHA from GHCR or (fallback) the tip of main."
echo "# After CI for all 9 repos is green, these should match published images."
echo

missing=0
for helm_key in api-gateway command-handler mailing-service message-sender event-loop payment-service chat-export-service business-events-new business-events-edited; do
  pkg="${PACKAGES[$helm_key]}"
  repo="${REPOS[$helm_key]}"
  source="ghcr"
  sha="$(sha_from_ghcr "$pkg" || true)"

  if [ -z "$sha" ]; then
    source="main"
    sha="$(sha_from_main "$repo" || true)"
  fi

  if [ -z "$sha" ]; then
    echo "# ERROR: could not resolve SHA for ${helm_key} (package ${pkg}, repo ${repo})" >&2
    sha="0000000000000000000000000000000000000000"
    missing=$((missing + 1))
  else
    echo "# ${helm_key}: ${sha} (via ${source})" >&2
  fi

  cat <<YAML
${helm_key}:
  image:
    tag: "${sha}"
    pullPolicy: IfNotPresent

YAML
done

if [ "$missing" -gt 0 ]; then
  echo "# $missing service(s) unresolved." >&2
  echo "# Fix auth: gh auth refresh -h github.com -s read:packages,repo" >&2
  echo "# Or set GH_TOKEN to a PAT with read:packages (and repo for private sources)." >&2
  exit 1
fi

echo "# All 8 services resolved." >&2
