#!/usr/bin/env bash
# Fetch the latest GHCR image tag (commit SHA) for each ChatDetective service and print a
# values-k3s-images.yaml snippet ready to paste into /root/chatdetective/values-k3s-images.yaml.
#
# Requires GitHub CLI with package read access:
#   gh auth login
#
# Usage:
#   ./scripts/fetch-image-tags.sh
#   ./scripts/fetch-image-tags.sh > /root/chatdetective/values-k3s-images.yaml
#
# GHCR package names (IMAGE_NAME in each repo's deploy.yml) differ from Helm chart keys for
# the business-events handlers — the mapping is handled below.
set -euo pipefail

ORG="${ORG:-ChatDetectiveORG}"

# Helm chart key -> GHCR package name
declare -A PACKAGES=(
  [api-gateway]=api-gateway
  [command-handler]=command-handler
  [message-sender]=message-sender
  [event-loop]=event-loop
  [payment-service]=payment-service
  [chat-export-service]=chat-export-service
  [business-events-new]=business-events-new-handler
  [business-events-edited]=business-events-edited-handler
)

if ! command -v gh >/dev/null; then
  echo "ERROR: gh (GitHub CLI) is required. Install: https://cli.github.com/" >&2
  exit 1
fi

latest_sha() {
  local pkg="$1"
  # Prefer the most recent version whose tag looks like a full git SHA (40 hex chars).
  gh api "/orgs/${ORG}/packages/container/${pkg}/versions?per_page=20" \
    --jq '.[].metadata.container.tags[]' \
    | grep -E '^[0-9a-f]{40}$' \
    | head -1
}

echo "# Generated by fetch-image-tags.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "# Verify each SHA matches the intended commit before deploying."
echo

missing=0
for helm_key in api-gateway command-handler message-sender event-loop payment-service chat-export-service business-events-new business-events-edited; do
  pkg="${PACKAGES[$helm_key]}"
  sha="$(latest_sha "$pkg" || true)"
  if [ -z "$sha" ]; then
    echo "# WARNING: no SHA tag found for ghcr.io/${ORG}/${pkg}" >&2
    sha="0000000000000000000000000000000000000000"
    missing=$((missing + 1))
  fi
  cat <<YAML
${helm_key}:
  image:
    tag: "${sha}"
    pullPolicy: IfNotPresent

YAML
done

if [ "$missing" -gt 0 ]; then
  echo "# $missing package(s) missing SHA tags — fix before deploy." >&2
  exit 1
fi

echo "# All 8 services resolved."
